---
- name: Using ServiceNow Collection
  hosts: localhost
  gather_facts: no
  collections:
    - servicenow.servicenow

  tasks:
  - name: Create an incident
    snow_record:
      username: ansible
      password: Ansible1
      instance: dev17663
      state: present
      data:
        short_description: "This is a test incident opened by Ansible"
        severity: 3
       
